# Generated by Django 4.1.3 on 2022-11-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategorimodel',
            table='kategori',
        ),
    ]
